<?php
/**
 * @file
 */

// Include theme definiation and preprocess
module_load_include('inc', 'commentz', 'theme/theme');

// @todo If node is supposed to see commentz
module_load_include('inc', 'commentz', 'commentz.form');

/**
 * Implements hook_menu().
 */
function commentz_menu() {
  $items['commentz/%/delete'] = array(
    'page callback' => 'commentz_delete_page',
    'page arguments' => array(1),
    'access callback' => TRUE,
    //'access arguments' => array('delete own comment'),
    'delivery callback' => 'ajax_deliver',
    'type' => MENU_CALLBACK,
    'file' => 'commentz.pages.inc',
  );
  $items['commentz/%/edit'] = array(
    'page callback' => 'commentz_edit_page',
    'page arguments' => array(1),
    'access callback' => TRUE,
    //'access arguments' => array('delete own comment'),
    'delivery callback' => 'ajax_deliver',
    'type' => MENU_CALLBACK,
    'file' => 'commentz.pages.inc',
  );
  $items['commentz/response/%/delete'] = array(
    'page callback' => 'commentz_response_delete_page',
    'page arguments' => array(2),
    'access callback' => TRUE,
    //'access arguments' => array('delete own commentz response'),
    'delivery callback' => 'ajax_deliver',
    'type' => MENU_CALLBACK,
    'file' => 'commentz.pages.inc',
  );
  $items['commentz/%/reply'] = array(
    'page callback' => 'commentz_reply',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'access arguments' => array('access comments'),
    'delivery callback' => 'ajax_deliver',
    'type' => MENU_CALLBACK,
    'file' => 'commentz.pages.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function commentz_permission() {
  return array(
    'administer commentz' => array(
      'title' => t('Administer commentz and commentz settings'),
    ),
    'access commentz' => array(
      'title' => t('View commentz'),
    ),
    'post commentz' => array(
      'title' => t('Post commentz'),
    ),
    'edit commentz' => array(
      'title' => t('Edit commentz'),
    ),
    'edit own commentz' => array(
      'title' => t('Edit own commentz'),
    ),

    'delete own commentz' => array(
      'title' => t('Delete own commentz'),
    ),
    'delete commentz' => array(
      'title' => t('Delete commentz'),
    ),

  );
}

/**
 * Implement hook_entity_info().
 */
function commentz_entity_info() {
  $return = array(
    'commentz' => array(
      'label' => t('Commentz'),
      'base table' => 'commentz',
      // Use the default label() and uri() functions
      'label callback' => 'entity_class_label',
      'uri callback' => 'entity_class_uri',
      'fieldable' => FALSE,
      'controller class' => 'EntityAPIController',
      'entity keys' => array(
        'id' => 'cid',
      ),
      'bundles' => array(),
      'static cache' => FALSE,
    ),
  );
  return $return;
}

function commentz_node_view($node) {
  $node->content['commentz'] = commentz_node_additions($node);
}

function commentz_node_additions($node) {

  if (!user_access('access commentz')) {
    return array();
  }

  $additions = array();
  // @todo correct permissions
  if (1==1) {
    if ($commentz_all = commentz_load_all($node->nid)) {
      $build = commentz_view_multiple($commentz_all['data'], $node);
      $additions['commentzs'] = $build;
      $additions['commentzs']['#count'] = $commentz_all['count'];
    }
  }

  if (user_access('post commentz')) {
    $build = drupal_get_form('commentz_form', $node);
    $additions['commentz_form'] = $build;
  }

  $additions += array(
    '#theme' => 'commentz_wrapper',
    '#node' => $node,
    'commentzs' => array(),
    'commentz_form' => array(),
    '#attached' => array(
      'css' => array(drupal_get_path('module', 'commentz') . '/commentz.css'),
      'js' => array(drupal_get_path('module', 'commentz') . '/commentz.js')
    )
  );
  $additions['commentz_form'] = $build;

  return $additions;
}


function commentz_save($commentz) {
  $entity = entity_create('commentz', (array) $commentz);
  $entity_wrapper = entity_metadata_wrapper('commentz', $entity);
  return $entity_wrapper->save();
}

function commentz_load_all($nid) {
  $commentz_all = entity_load('commentz', FALSE, array('nid' => $nid));
  $nested_commentzs = array('data' => array(), 'count' => NULL);
  $commentz_count = 0;
  foreach($commentz_all as $cid => $commentz) {
    if ($commentz->pid == 0) {
      if (!isset($nested_commentzs['data'][$commentz->cid])) {
        $nested_commentzs['data'][$commentz->cid]['responses'] = array();
      }
      $nested_commentzs['data'][$commentz->cid] += (array)$commentz;
      $nested_commentzs['count'] = ++ $commentz_count;
    } else {
      $nested_commentzs['data'][$commentz->pid]['responses'][$commentz->cid] = (array)$commentz;
    }
  }
  return $nested_commentzs;
}

function commentz_view($commentz, $node) {
  $build = array(
    '#theme' => 'commentz',
    '#comment' => $commentz,
    '#node' => $node,
    'links' => array(
      '#theme' => 'links',
      '#links' => commentz_links($commentz, $node),
      '#attributes' => array('class' => array('links', 'inline')),
    ),
  );
  if (!empty($commentz['responses'])) {
    $build['commentz_responses'] = commentz_response_view_multiple($commentz['responses']);
  }
  $build['commentz_response_form'] = drupal_get_form('commentz_response_form', $commentz);
  return $build;
}

function commentz_view_multiple($commentzs, $node) {
  $build = array();
  foreach($commentzs as $comment_id => $commentz) {
    $build[$commentz['cid']] = commentz_view($commentz, $node);
  }
  return $build;
}

function commentz_response_view_multiple($commentz_responses) {

  $build = array();
  foreach($commentz_responses as $commentz_id => $response) {
    $build[$response['cid']] = commentz_response_view($response);
  }
  return $build;
}



function commentz_response_view($response) {
  $build = array(
    '#theme' => 'commentz_response',
    '#response' => $response,
  );

  // User can delete only their own response.
  global $user;
  if ((user_access('delete own commentz') && $user->uid == $response['uid']) || user_access('delete commentz')) {
    $build['#delete_link'] = theme('commentz_response_delete_link', array('response_id' => $response['cid']));
  } else {
    $build['#delete_link'] = NULL;
  }
  return $build;
}

function commentz_get_avatar($uid) {

  $user = user_load(intval($uid));
  global $user;
  $variables = array(
    'style_name' => 'commentz_avatar',
    'path' => file_load($user->picture)->uri,
    'alt' => $user->name,
    'width' => 36,
    'height' => 36,
  );
  return theme_image_style($variables);
}

/**
 * Helper function, build links for an individual comment.
 *
 * Adds reply, edit, delete etc. depending on the current user permissions.
 *
 * @param $comment
 *   The comment object.
 * @param $node
 *   The node the comment is attached to.
 * @return
 *   A structured array of links.
 */
function commentz_links($commentz, $node) {
  $links = array();
  global $user;


  if (user_access('delete own commentz') && $commentz['uid'] == $user->uid) {
    $links['commentz-delete'] = array(
      'title' => t('delete'),
      'href' => "commentz/" . $commentz['cid'] . "/delete",
      'html' => TRUE,
      'attributes' => array('class' => array('use-ajax'))
    );
  }
  if (user_access('edit own commentz') && $commentz['uid'] == $user->uid) {
    $links['commentz-edit'] = array(
      'title' => t('edit'),
      'href' => "commentz/" . $commentz['cid'] . "/edit",
      'html' => TRUE,
      'attributes' => array('class' => array('use-ajax'))
    );
  }

  if (user_access('post commentz')) {
    $links['commentz-add-response'] = array(
      'title' => t('reply'),
      'href' => "javascript:;",
      'html' => FALSE,
      'external' => TRUE,
      'attributes' => array('class' => array('commentz-add-response-link'))
    );
  } else {
    $links['commentz-add-response'] = array(
      'title' => t('login to reply'),
      'href' => "user/login",
      'attributes' => array('class' => array('commentz-add-response-link'))
    );
  }
  return $links;
}

function commentz_load($cid) {
  $commentz = entity_load('commentz', array($cid));
  return (array) reset($commentz);
}

function commentz_delete($cid) {
  db_delete('commentz')
    ->condition('cid', $cid, '=')
    ->execute();

  db_delete('commentz')
    ->condition('pid', $cid, '=')
    ->execute();
}

function commentz_response_delete($response_id) {
  db_delete('commentz')
  ->condition('cid', $response_id, '=')
  ->execute();
}

/**
 *
 * Implements hook_node_delete().
 *
 * Delete all the commentz for the node that just got
 * deleted.
 */
function commentz_node_delete($nid) {
  db_delete('commentz')
    ->condition('nid', $nid, '=')
    ->execute();
}


function _debug($data, $die = true) {
  echo "<pre>";
  print_r($data);
  echo "</pre>";
  if ($die)
    die();
}